// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ConfirmSubmitController from "./confirm_submit_controller"
application.register("confirm-submit", ConfirmSubmitController)

import PlayerController from "./player_controller"
application.register("player", PlayerController)

import SorterController from "./sorter_controller"
application.register("sorter", SorterController)
